Lesson 17 Подготовка приложения и деплой
Mr-Slavka/test-guru pull request #16
Opened 2022-10-13 21:17 UTC by Mr-Slavka

2022-10-14 05:40 UTC, BubuntuClu requested changes

2022-10-14 05:40 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +      if @test.questions.present?
зачем пользователю видеть тест, который он не может проходить? надо решить эту проблему другим способом

2022-10-14 05:40 UTC, BubuntuClu commented on app/mailers/feedback_mailer.rb
> +    @email = User.find_by(type: 'Admin').email
`Admin.first.email`?

2022-10-16 08:20 UTC, Mr-Slavka commented on app/controllers/tests_controller.rb
> +      if @test.questions.present?
Исправил

2022-10-16 16:08 UTC, BubuntuClu requested changes

2022-10-16 16:08 UTC, BubuntuClu commented on app/views/tests/_test.html.erb
> +    <%if  test.questions.present?%>
смотри, я добавил первый вопрос и тест начал отображаться. ответов в вопросе нет, да и вдруг я задумал 10 вопросов на тест. тест еще не готов к отображению.

завязяывать логику на количестве вопросов и ответах в них - неправильная логика

2022-10-16 16:08 UTC, BubuntuClu commented on app/views/tests/_test.html.erb
> +    <%if  test.questions.present?%>
ну и тут отступов не хватает

2022-10-16 16:08 UTC, BubuntuClu commented on app/views/tests/_test.html.erb
> +  <%if  test.questions.present?%>
а, тут поправил отступы

2022-10-16 16:10 UTC, BubuntuClu requested changes

2022-10-16 16:10 UTC, BubuntuClu commented on db/migrate/20221015155135_add_current_question_on_delete_options.rb
> +    change_table :test_passages do |t|
можно решить эту проблему без этого вмешательства в таблицу. правлиьно задать `dependent: :destroy`. порядок задачи ассоциаций в моделях имеет значение

2022-10-16 16:10 UTC, BubuntuClu commented on db/migrate/20221015155135_add_current_question_on_delete_options.rb
> +    change_table :test_passages do |t|
такой миграцией, ты очистишь всем текущий процесс в тестах

2022-10-17 07:33 UTC, Mr-Slavka commented on app/views/tests/_test.html.erb
> +    <%if  test.questions.present?%>
добавил возможность опубликовать / скрыть тест для администратора

2022-10-17 07:34 UTC, Mr-Slavka commented on db/migrate/20221015155135_add_current_question_on_delete_options.rb
> +    change_table :test_passages do |t|
убрал миграцию, поменял порядок ассоциаций в test

2022-10-17 19:42 UTC, BubuntuClu requested changes

2022-10-17 19:42 UTC, BubuntuClu commented on app/views/tests/_test.html.erb
> +  <%if  test.published%>
допустим у тебя в базе хранится 100500 тестов. чтобы отобразить страницу с тестами, ты достаешь все 100500 тестов, а из них к прохождению готовы только 5. ты делаешь сильно много лишней работы. сначала получаешь много лишних данных, а потом все эти данные итерируешь чтобы проверить опубликован он или нет.

надо просто получить изначально только опубликованные тесты, облегчай работу приложения максимально на уровне БД. запросы твои помощники в этом деле

2022-10-17 20:42 UTC, Mr-Slavka commented on app/views/tests/_test.html.erb
> +  <%if  test.published%>
исправил

2022-10-18 11:46 UTC, merged