Creating badges
Mr-Slavka/test-guru pull request #17
Opened 2022-10-21 20:20 UTC by Mr-Slavka

2022-10-22 05:57 UTC, VidgarVii requested changes

2022-10-22 05:57 UTC, VidgarVii commented on app/controllers/admin/badges_controller.rb
> +  end
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file

2022-10-22 05:57 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +        added_badges.each { |badge| current_user.badges.push(badge) if badge.present? }
можно и лучше сделать без итераций и проверок
`current_user.badges.push(badge)`
и логику выдачу баджей можно вынести в сервис BadgesService.

2022-10-22 05:57 UTC, VidgarVii commented on app/services/badges_service.rb
> +    end
подобный процедурный подход показывает, что что-то не так в коде
можно просто заменить each на select и тогда вернётся коллекция где условие было удовлетворительна

2022-10-22 05:57 UTC, VidgarVii commented on app/services/badges_service.rb
> +    def all_tests_passages_
не корректное название метода

2022-10-22 05:57 UTC, VidgarVii commented on app/services/badges_service.rb
> +    end
предлагаю не мешать всё в 1 кучу. Разделый логику по проверки правил и выдачи баджа

2022-10-22 05:57 UTC, VidgarVii commented on app/services/badges_service.rb
> +      badge = Badge.find_by(rule: 'all_tests_passages')
очень плохой подход для каждого правила делать запрос в базу. А если правил будет 100? 1000? И для каждого делать запрос? Это надо учитывать. Такое будет работать очень долго, если база вообще выдержит.
Можно 1 раз получить список баджей и при итерации проверять достоен юзер этот бадж получить или нет

2022-10-22 05:57 UTC, VidgarVii commented on app/services/badges_service.rb
> +  end
Что станет с этим файлом если добавить еще сотню правил?

2022-10-24 09:02 UTC, Mr-Slavka commented on app/services/badges_service.rb
> +    end
Разделил

2022-10-24 09:02 UTC, Mr-Slavka commented on app/services/badges_service.rb
> +      badge = Badge.find_by(rule: 'all_tests_passages')
Исправил

2022-10-24 09:03 UTC, Mr-Slavka commented on app/services/badges_service.rb
> +  end
Вынес правила в модуль

2022-10-24 13:44 UTC, VidgarVii requested changes

2022-10-24 13:44 UTC, VidgarVii commented on app/assets/javascripts/utilities/show_category_field.js
> +}
https://github.com/Mr-Slavka/test-guru/pull/17#discussion_r1002360616

2022-10-24 13:44 UTC, VidgarVii commented on app/models/badges_user.rb
> +  end
пора уже перестать совершать такие стилистические ошибки!

2022-10-24 13:44 UTC, VidgarVii commented on app/models/badges_user.rb
> +
всегда пользуйся rubocop
код пишут с 1 строчки и без лишних пробелов

2022-10-25 10:42 UTC, merged