Lesson5 association
Mr-Slavka/test-guru pull request #4
Opened 2022-06-30 14:34 UTC by Mr-Slavka

2022-06-30 19:17 UTC, BubuntuClu requested changes

2022-06-30 19:17 UTC, BubuntuClu commented on app/models/test.rb
> +    has_many :users, through: :stories, dependent: :destroy
смотри что ты мог тут вылить в прод.
сделал связь теста с пользователями, которые его проходили и указал опцию связи на удаление.

то есть ты удаляешь какой-то тест и все пользователи которые его проходили удаляться вместе с ним. ты уверен что хочешь такой функционал?)

на самом деле чтобы такого не допустить есть защита, для маньяков типа тебя) опция `dependent` не работает на ассоциациях построенных с использованием `through`.

так что не стоит бездумно писать код, невсегда разработчики рельсы могут предусмотреть опасное поведение

2022-06-30 19:17 UTC, BubuntuClu commented on app/models/user.rb
> +  has_many :tests, through: :stories, dependent: :destroy
тут тоже самое

2022-06-30 19:17 UTC, BubuntuClu commented on db/migrate/20220615145451_create_tests.rb
> +      t.references :author, foreign_key: { to_table: :users }, null: false
править миграции задним числом нельзя. откати эту правку и через новую миграцию внеси изменения

2022-06-30 19:17 UTC, BubuntuClu commented on db/schema.rb
> +    t.bigint "author_id", null: false
править миграции задним числом нельзя. откати эту правку и через новую миграцию внеси изменения

2022-07-02 14:06 UTC, Mr-Slavka commented on app/models/test.rb
> +    has_many :users, through: :stories, dependent: :destroy
Понял. Исправил

2022-07-02 14:06 UTC, Mr-Slavka commented on app/models/user.rb
> +  has_many :tests, through: :stories, dependent: :destroy
Исправил

2022-07-02 14:06 UTC, Mr-Slavka commented on db/migrate/20220615145451_create_tests.rb
> +      t.references :author, foreign_key: { to_table: :users }, null: false
Создал новую миграцию

2022-07-02 14:07 UTC, Mr-Slavka commented on db/schema.rb
> +    t.bigint "author_id", null: false
Создал новую миграцию

2022-07-02 19:34 UTC, merged